require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Gatabase
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Do not swallow errors in after_commit/after_rollback callbacks.
    config.active_record.raise_in_transactional_callbacks = true

    config.counties = ["Antrim",
                       "Armagh",
                       "Carlow",
                       "Cavan",
                       "Clare",
                       "Cork",
                       "Derry",
                       "Donegal",
                       "Down",
                       "Dublin",
                       "Fermanagh",
                       "Galway",
                       "Kerry",
                       "Kildare",
                       "Kilkenny",
                       "Laois",
                       "Leitrim",
                       "Limerick",
                       "Longford",
                       "Louth",
                       "Mayo",
                       "Meath",
                       "Monaghan",
                       "Offaly",
                       "Roscommon",
                       "Sligo",
                       "Tipperary",
                       "Tyrone",
                       "Waterford",
                       "Westmeath",
                       "Wexford",
                       "Wicklow"]

    config.antrim = ["All Saints",
                     "Ardoyne Kickhams",
                     "Cardinal O'Donnells",
                     "Ballymoney",
                     "Carey Faughs",
                     "Clooney Gaels HC",
                     "Con Magees",
                     "Cushendun Emmets",
                     "Creggan Kickhams",
                     "Dunloy Cuchullains",
                     "Erin\'s Own",
                     "Éire Óg",
                     "Gort na Móna",
                     "Glen Rovers",
                     "Glenshesk",
                     "Henry Joy McCracken\'s",
                     "John Mitchel\'s",
                     "Lagmore Gaels",
                     "Lámh Dhearg",
                     "Laochra Loch Lao",
                     "Latharna Óg",
                     "Loch Mór Dál gCais",
                     "McQuillan\'s",
                     "Michael Davitt\'s",
                     "Michael Dwyer\'s",
                     "Na Fuiseoige",
                     "Naomh Eoin",
                     "Naomh Mhuire",
                     "O\'Donovan Rossa",
                     "Oisín Glenariff",
                     "Patrick Pearse\'s",
                     "Patrick Sarsfields",
                     "Roger Casement\'s",
                     "Ruairí Óg",
                     "Sean Martin\'s",
                     "Sean McDermott\'s",
                     "Sean Stinson\'s",
                     "Loughgiel Shamrocks",
                     "Shane O'Neill\'s",
                     "St Agnes'",
                     "St Brigid\'s",
                     "St Comgall\'s",
                     "St Enda\'s",
                     "St Ergnat\'s",
                     "St Gall\'s",
                     "St James\'",
                     "St John\'s",
                     "St Joseph\'s",
                     "St Malachy\'s",
                     "St Mary\'s",
                     "St Mary's GFC",
                     "St Mary\'s",
                     "St Paul\'s",
                     "St Patrick\'s",
                     "St Teresa\'s",
                     "Tir-na-nÓg"]

    config.armagh = ["O'Neill\'s GAC, An Port Mór",
                     "Annaghmore Pearses Gaelic Football Club (GFC)",
                     "Cúchulainn\'s Hurling Club (HC)",
                     "Armagh Harps",
                     "Pearse Óg Gaelic Athletic Club (GAC)",
                     "Ballyhegan Davitts",
                     "Ballymacnab Round Towers",
                     "St Brenda\'s Camogie Club",
                     "Ballymacnab",
                     "Belleeks Laurence O'Toole\'s",
                     "St. Patrick\'s, Carrickcruppen",
                     "Clady Sean South\'s",
                     "Shane O'Neill\'s, Camloch",
                     "Craobh Rua Camloch HC",
                     "Clann Éireann Lurgan",
                     "Clonmore Robert Emmet\'s",
                     "Collegeland O'Rahilly\'s",
                     "Thomas Davis Corrinshego",
                     "Éire Óg Craigavon",
                     "Crosmaglen Rangers",
                     "Cullaville Blues",
                     "Phelim Brady\'s Darkley",
                     "Derrymacash St Enda\'s Camogie Club",
                     "Derrynoose St Mochua\'s",
                     "Dorsey Emmet\'s",
                     "Dromintee St. Patrick\'s",
                     "Forkhill Peadar Ó Doirnín",
                     "Granemore St Mary\'s",
                     "Grange St. Colmcille\'s",
                     "High Moss Sarsfields",
                     "Keady Michael Dwyer\'s",
                     "Keady Lámh Dhearg HC",
                     "Killeavy St. Monina\'s",
                     "Lissummon",
                     "Lurgan Clan na Gael",
                     "Lurgan Sean Treacy\'s HC",
                     "Madden Raparees",
                     "St Joseph\'s Camogie Club, Madden",
                     "Maghery Sean MacDermott\'s GAC",
                     "Middletown Eoghan Ruadh (football)",
                     "Na Fianna (hurling)",
                     "St John\'s (camogie)",
                     "Mullaghbawn Cuchullian\'s",
                     "Mullabrack O'Donovan Rossa",
                     "St Michael\'s, Newtownhamilton",
                     "St Michael\'s GFC, Killean",
                     "St. Patrick\'s Cullyhanna",
                     "St. Paul\'s Lurgan",
                     "St Peter\'s GAC Lurgan",
                     "Portadown St Malachy\'s HC",
                     "Portadown Tír na nÓg",
                     "Poyntzpass Redmond O'Hanlon\'s",
                     "Silverbridge Harps",
                     "Tullysaran O\'Connell\'s",
                     "Whitecross St. Killian\'s",
                     "Wolfe Tones, Derrymacash"]

    config.carlow = ["Asca",
                     "Ballinabranna",
                     "Ballon",
                     "Ballinkillen",
                     "Carlow Town HC",
                     "Clonmore",
                     "Éire Óg",
                     "Erin\'s Own",
                     "Fenagh",
                     "Fighting Cocks",
                     "Grange",
                     "Kildavin/Clonegal",
                     "Kilbride",
                     "Leighlinbridge",
                     "Milford",
                     "Mount Leinster Rangers",
                     "Michael Davitts",
                     "Naomh Bríd",
                     "Naomh Eoin",
                     "O'Hanrahan\'s",
                     "Old Leighlin",
                     "Palatine",
                     "Rathvilly",
                     "St Andrew\'s",
                     "St Mullin\'s",
                     "St Patrick\'s",
                     "Tinryland"]

    config.cavan = ["Arvagh",
                    "Bailieboro Shamrocks",
                    "Ballinagh",
                    "Ballyhaise",
                    "Belturbet Rory O\'Moore\'s",
                    "Butlersbridge",
                    "Castlerahan",
                    "Cavan Gaels",
                    "Cootehill Celtic",
                    "Corlough",
                    "Cornafean",
                    "Crosserlough",
                    "Mullagh Cúchullains",
                    "Denn",
                    "Drumalee",
                    "Drumgoon",
                    "Drumlane",
                    "Drung",
                    "East Cavan Gaels GAA Hurling Club", 
                    "Gowna", 
                    "Kildallon", 
                    "Kill Shamrocks", 
                    "Killeshandra", 
                    "Killinkere", 
                    "Killygarry",
                    "Kingscourt Stars",
                    "Knockbride",
                    "Lacken Celtic",
                    "Laragh United",
                    "Lavey",
                    "Macauley Geals, Mullahorn",
                    "Maghera MacFinns",
                    "Mountnugent",
                    "Mullahoran",
                    "Munterconnaught",
                    "Ramor United",
                    "Redhills",
                    "Shannon Gaels",
                    "Shercock",
                    "Swanlinbar St Mary\'s",
                    "Templeport St Aidan\'s"]

    config.clare = ["Ballyea",
                    "Ballyvaughan",
                    "Banner",
                    "Bodyke",
                    "Broadford",
                    "Clarecastle",
                    "Clonboney",
                    "Clondegad",
                    "Clonlara",
                    "Clooneyquin",
                    "Coolmeen",
                    "Cooraclare",
                    "Corofin",
                    "Cratloe",
                    "Crusheen",
                    "Doonbeg",
                    "Éire Óg, Inis",
                    "Ennistymon",
                    "Feakle",
                    "Inagh-Kilnamona",
                    "Kildysart",
                    "Kilfenora",
                    "Kilkee Bealatha",
                    "Killimer",
                    "Killanena",
                    "Kilmaley",
                    "Kilmihil",
                    "Kilmurry Ibrickane",
                    "Kilrush Shamrocks",
                    "Liscannor",
                    "Lissycasey",
                    "Meelick",
                    "Michael Cusack's",
                    "Moy",
                    "Naomh Eoin",
                    "Newmarket-on-Fergus",
                    "O\'Callaghan Mills",
                    "O\'Curry\'s",
                    "Ogonnelloe",
                    "Parteen",
                    "Ruan",
                    "Scariff",
                    "Shannon Gaels",
                    "Sixmilebridge",
                    "Smith O\'Brien\'s",
                    "St Breckan\'s",
                    "St Joseph\'s Doora-Barefield",
                    "St Joseph\'s, Milltown Malbay",
                    "St. Senan\'s, Kilkee",
                    "Tubber",
                    "Tulla",
                    "West Clare Gaels",
                    "Whitegate",
                    "Wolfe Tones na Sionna"]

    config.cork = ["Abbey Rovers",
                   "Adrigole",
                   "Aghabullogue",
                   "Aghada",
                   "Aghinagh",
                   "Araglen",
                   "Argideen Rangers",
                   "Awbeg Rangers",
                   "Ballinacurra",
                   "Ballinascarthy",
                   "Ballincollig",
                   "Ballinhassig",
                   "Ballinora",
                   "Ballinure",
                   "Ballyclough",
                   "Ballydesmond",
                   "Ballygarvan",
                   "Ballygiblin",
                   "Ballyhea",
                   "Ballyhooly",
                   "Ballymartle",
                   "Ballyphehane",
                   "Bandon",
                   "Banteer",
                   "Bantry Blues",
                   "Barryroe",
                   "Belgooly",
                   "Bere Island",
                   "Bishopstown",
                   "Blackrock",
                   "Blarney",
                   "Boherbue",
                   "Brian Dillons",
                   "Bride Rovers",
                   "Buttevant",
                   "Béal Átha\'n Ghaorthaidh",
                   "CIT",
                   "Canovee",
                   "Carbery Rangers",
                   "Carrigaline",
                   "Carrignavar",
                   "Carrigtwohill",
                   "Castlehaven",
                   "Castlelyons",
                   "Castlemagner",
                   "Castlemartyr",
                   "Castletownbere",
                   "Castletownroche",
                   "Charleville",
                   "Churchtown",
                   "Clann na nGael",
                   "Clonakilty",
                   "Clondrohid",
                   "Cloughduv",
                   "Cloyne",
                   "Clyda Rovers",
                   "Cobh",
                   "Courcey Rovers",
                   "Crosshaven",
                   "Cullen",
                   "Deel Rovers",
                   "Delaney Rovers",
                   "Diarmuid Ó Mathúnas",
                   "Dohenys",
                   "Doneraile",
                   "Donoughmore",
                   "Douglas",
                   "Dripsey",
                   "Dromina",
                   "Dromtarriffe",
                   "Dungourney",
                   "Éire Óg",
                   "Erin\'s Own",
                   "Fermoy",
                   "Fr. O\'Callaghan's",
                   "Fr. O\'Neills",
                   "Freemount",
                   "Gabriel Rangers",
                   "Garnish",
                   "Glanmire",
                   "Glanworth",
                   "Gleann na Laoi",
                   "Glen Rovers",
                   "Glenbower Rovers",
                   "Glengarriff",
                   "Glenlara",
                   "Glenville",
                   "Goleen",
                   "Grange",
                   "Grenagh",
                   "Gurranabraher",
                   "Harbour Rovers",
                   "Ilen Rovers", 
                   "Inniscarra",
                   "Iveleary",
                   "Kanturk",
                   "Kilbree",
                   "Kilbrin",
                   "Kilbrittain",
                   "Kildorrery",
                   "Killavullen",
                   "Killeagh",
                   "Kilmacabea",
                   "Kilmeen",
                   "Kilmichael",
                   "Kilmurry",
                   "Kilnamartyra",
                   "Kilshannig",
                   "Kilworth",
                   "Kinsale",
                   "Kiskeam",
                   "Knocknagree",
                   "Laochra Óg",
                   "Liscarroll",
                   "Lisgoold",
                   "Lough Rovers",
                   "Lyre",
                   "Macroom",
                   "Mallow",
                   "Mayfield",
                   "Meelin",
                   "Midleton",
                   "Milford",
                   "Millstreet",
                   "Mitchelstown",
                   "Muintir Bháire",
                   "Na Piarsaigh",
                   "Naomh Abán",
                   "Nemo Rangers",
                   "Newcestown",
                   "Newmarket",
                   "Newtownshandrum",
                   "O\'Donovan Rossa",
                   "Passage West",
                   "Randal Og",
                   "Rathpeacon",
                   "Redmonds",
                   "Rochestown",
                   "Rockchapel",
                   "Russell Rovers",
                   "Sam Maguires",
                   "Sarsfields",
                   "Shamrocks",
                   "Shanballymore",
                   "Shandon Rovers",
                   "Sliabh Rua",
                   "St Catherine\'s",
                   "St Colum\'s",
                   "St Finbarr\'s",
                   "St Ita\'s",
                   "St James\'",
                   "St Marys's",
                   "St Michael's",
                   "St Nicholas'",
                   "St Oliver Plunkett's",
                   "St Vincent's",
                   "Tadhg MacCarthaigh",
                   "Tracton",
                   "Tullylease",
                   "UCC",
                   "Urhan",
                   "Valley Rovers",
                   "Watergrasshill",
                   "White's Cross",
                   "Whitechurch",
                   "Youghal"]

    config.derry = ["Ardmore",
                    "Ballerin",
                    "Ballinascreen",
                    "Ballinderry",
                    "Ballymaguigan",
                    "Banagher",
                    "Bellaghy",
                    "Castledawson",
                    "Claudy",
                    "Craigbane",
                    "Desertmartin",
                    "Doire Colmcille",
                    "Doire Trasna",
                    "Drum",
                    "Drumsurn",
                    "Dungiven",
                    "Eoghan Rua",
                    "Faughanvale",
                    "Foreglen",
                    "Glack",
                    "Glen",
                    "Glenullin",
                    "Greenlough",
                    "Kevin Lynch\'s Hurling Club",
                    "Kilrea",
                    "Lavey",
                    "Limavady",
                    "Lissan",
                    "Loup",
                    "Magherafelt",
                    "Magilligan",
                    "Moneymore",
                    "Na Magha",
                    "Newbridge",
                    "Ógra Colmcille",
                    "Seán Dolans",
                    "Slaughtmanus",
                    "Slaughtneil",
                    "Steelstown",
                    "Swatragh"]

    config.donegal = ["Aodh Ruadh, Ballyshannon",
                      "Ardara",
                      "Buncrana",
                      "Burt",
                      "Carndonagh",
                      "Cloughaneely",
                      "Dungloe",
                      "Fanad Gaels",
                      "Four Masters",
                      "Gaoth Dobhair",
                      "Glenfin",
                      "Glenswilly",
                      "Kilcar",
                      "Killybegs",
                      "Letterkenny Gaels",
                      "Malin",
                      "Milford",
                      "Moville",
                      "Na Dúnaibh (Downings)",
                      "Na Rossa",
                      "Naomh Bríd",
                      "Naomh Colmcille",
                      "Naomh Columba",
                      "Naomh Conaill",
                      "Naomh Muire",
                      "Naomh Pádraig, Lifford",
                      "Naomh Pádraig, Muff",
                      "Naomh Ultan",
                      "Pettigo",
                      "Red Hughs, Killygordon",
                      "Robert Emmet\'s",
                      "Réalt Na Mara, Bundoran",
                      "Setanta",
                      "Seán Mac Cumhaill\'s",
                      "St. Eunan\'s",
                      "St. Mary\'s, Convoy",
                      "St. Michael\'s",
                      "St. Naul\'s",
                      "Termon",
                      "Urris"]

    config.down = ["Aghaderg-Ballyvarley",
                   "An Riocht",
                   "Annaclone",
                   "Annsborough",
                   "Ardglass",
                   "Atticall",
                   "Ballela",
                   "Ballycran",
                   "Ballygalget",
                   "Ballyholland",
                   "Ballykinlar",
                   "Ballymartin",
                   "Bredagh",
                   "Bright",
                   "Bryansford- Website",
                   "Burren",
                   "Carryduff",
                   "Castlewellan",
                   "Clann na Banna",
                   "Clonduff",
                   "Darragh Cross",
                   "Dromara",
                   "Drumaness",
                   "Drumgath",
                   "Dundrum",
                   "Glasdrumman",
                   "Glenn",
                   "Kilclief",
                   "Kilcoo",
                   "Killyleagh",
                   "Liatroim",
                   "Longstone",
                   "Loughinisland",
                   "Mayobridge",
                   "John Mitchel",
                   "Mourne HC",
                   "Newry Bosco",
                   "Newry Shamrocks",
                   "Portaferry",
                   "Rostrevor",
                   "Russell Gaelic Union, Downpatrick",
                   "Saul",
                   "Saval",
                   "St John's",
                   "St Michael's",
                   "St Paul's",
                   "Teconnaught",
                   "Tullylish",
                   "Warrenpoint"]


    config.dublin = ["Adamstown",
                     "Allied Irish Banks",
                     "Ballinteer Saint Johns",
                     "Ballyboden St. Enda's GAA",
                     "Ballyboughal",
                     "Ballyfermot de la Salle", "Ballymun Kickhams",
                     "Bank of Ireland",
                     "Beann Éadair",
                     "Castleknock",
                     "Civil Service GFC",
                     "Civil Service HC",
                     "Clann Mhuire",
                     "Clanna Gael Fontenoy",
                     "Clontarf", 
                     "Commercials Hurling Club",
                     "Craobh Chiaráin",
                     "Croi Ro Naofa",
                     "Crumlin",
                     "Cuala",
                     "Erin go Bragh",
                     "Erin's Hope",
                     "Erin's Isle",
                     "Faughs",
                     "Fingal Ravens, Rolestown",
                     "Fingallians",
                     "Foxrock-Cabinteely",
                     "Garda", "Garristown",
                     "Geraldine Morans",
                     "Good Counsel",
                     "Innisfails",
                     "Kevins",
                     "Kilmacud Crokes",
                     "Liffey Gaels",
                     "Lucan Sarsfields",
                     "Man O'War",
                     "Na Dubh Ghall",
                     "Na Fianna",
                     "Na Gaeil Óga",
                     "Naomh Barróg",
                     "Naomh Caoímhin Cillian",
                     "Naomh Fionnbarra",
                     "St. Maur's",
                     "Naomh Mearnóg",
                     "Naomh Ólaf",
                     "O'Dywer's",
                     "O'Tooles's",
                     "Park Rangers",
                     "Parnells",
                     "St Christophers/Paveh",
                     "Portobello",
                     "Raheny",
                     "Ranelagh Gaels",
                     "Réalt Dearg",
                     "Robert Emmets",
                     "Round Towers Clondalkin",
                     "Round Towers, Lusk",
                     "Rosmini Gaels",
                     "Samildánach CLG Bawnogue",
                     "Scoil Uí Chonaill",
                     "Setanta",
                     "Shankill",
                     "Skerries Harps",
                     "St. Annes",
                     "St Brendan's",
                     "St. Brigids",
                     "St Colmcilles",
                     "St. Finian's",
                     "St. Finnian's",
                     "St Francis Gaels",
                     "St. James Gaels",
                     "St Josephs/OCB",
                     "St Judes",
                     "St. Margarets",
                     "St. Marks Springfield Estate",
                     "St. Marys, Saggart",
                     "St. Monica's",
                     "St Oliver Plunketts/Eoghan Ruadh",
                     "St. Patrick's (D)",
                     "St. Patricks (P)",
                     "St. Peregrines",
                     "St Sylvesters",
                     "St Vincents",
                     "Starlights",
                     "Stars of Erin",
                     "Templeogue Synge Street",
                     "Thomas Davis",
                     "Transport Gaels",
                     "Trinity Gaels",
                     "Tyrrelstown",
                     "UCD",
                     "Wanderers ",
                     "Westmanstown Gaels",
                     "Whitehall Colmcille",
                     "Wild Geese",
                     "Western Gaels"]

    config.fermanagh = ["Teemore Shamrocks",
                        "Irvinestown St Molaise\'s", 
                        "Aughdrumsee St Macartan\'s", 
                        "Derrygonnelly Harps", 
                        "St Patrick\'s Donagh", 
                        "Tempo Maguires",
                        "Enniskillen Gaels",
                        "Roslea Shamrocks",
                        "Erne Gaels",
                        "Derrylin O\'Connell\'s",
                        "Belcoo O\'Rahilly\'s",
                        "Lisbellaw St Patrick\'s",
                        "Belnaleck Art McMurrough\'s",
                        "Maguiresbridge St Mary\'s",
                        "Lisnaskea Emmett\'s Hurling",
                        "Newtownbutler First Fermanagh\'s",
                        "Devenish St Mary\'s",
                        "Kinawley Brian Boru\'s",
                        "St Joseph\'s Ederney",
                        "Lisnaskea Emmett\'s",
                        "Brookeboro Heber Mc Mahons",
                        "Coa O\'Dwyer\'s",
                        "Knocks Grattan\'s"]

    config.galway = ["Abbeyknockmoy",
                     "Ahascragh-Fohenagh",
                     "An Spidéal",
                     "Annaghdown",
                     "Aran Islands",
                     "Ardrahan",
                     "Ballinasloe",
                     "Ballinderreen GAA",
                     "Ballygar",
                     "Barna",
                     "Beagh",
                     "Bearna/Na Forbacha",
                     "Caherlistrane",
                     "Caltra",
                     "Cappataggle",
                     "Carna-Caiseal",
                     "Carnmore",
                     "Carraroe",
                     "Castlegar",
                     "Claregalway",
                     "Clarinbridge",
                     "Clifden",
                     "Clonbur",
                     "Corofin",
                     "Cortoon Shamrocks",
                     "Craughwell",
                     "Dunmore McHales",
                     "Father Griffins-Éire Óg",
                     "Gaeil na Gaillimhe CLG",
                     "Glenamaddy",
                     "Glenysk",
                     "Gort",
                     "Headford",
                     "Kilbeacanty",
                     "Kilconieron",
                     "Kilconly",
                     "Killanin",
                     "Killererin",
                     "Killimor",
                     "Killimordaly",
                     "Kilkerrin-Clonberne",
                     "Kilnadeema-Leitrim",
                     "Kiltormer",
                     "Kinvara",
                     "Liam Mellows",
                     "Loughrea",
                     "Meelick/Eyrecourt",
                     "Menlo Emmet's",
                     "Menlough",
                     "Míchael Breathnach",
                     "Milltown",
                     "Monivea Abbeyknockmoy",
                     "Mountbellew-Moylough",
                     "Moycullen",
                     "Mullagh",
                     "Na Piarsaigh",
                     "Naomh Anna",
                     "Oranmore-Maree",
                     "Oughterard",
                     "Pádraig Pearse's",
                     "Portumna",
                     "Rahoon-Newcastle",
                     "Renvyle",
                     "Salthill-Knocknacarra", 
                     "Sarsfields", 
                     "Skehana", 
                     "Sylane",
                     "St Brendan\'s",
                     "St Colman\'s",
                     "St Columba\'s",
                     "St Gabriel\'s",
                     "St Grellan\'s",
                     "St James\'",
                     "St Kerill\'s",
                     "St Mary\'s, Athenry",
                     "St Michael\'s", 
                     "St Thomas\'", 
                     "Tommy Larkin's", 
                     "Tuam Hurling", 
                     "Tuam Stars",
                     "Turloughmore",
                     "Tynagh-Abbey-Duniry",
                     "Williamstown"]

    config.kerry = ["Abbeydorney",
                    "Annascaul",
                    "Ardfert",
                    "Asdee",
                    "Austin Stacks",
                    "Ballydonoghue",
                    "Ballyduff",
                    "Ballyheigue",
                    "Ballylongford",
                    "Ballymacelligott",
                    "Beale",
                    "Beaufort",
                    "Brosna",
                    "Caherdaniel",
                    "Castlegregory",
                    "Castleisland Desmonds",
                    "Causeway",
                    "Churchill",
                    "Clounmacon",
                    "Cordal",
                    "Cromane",
                    "Crotta O\'Neill's",
                    "Currow",
                    "Derrynane",
                    "Dingle",
                    "Dr. Crokes",
                    "Dromid Pearses",
                    "Duagh",
                    "East Kerry",
                    "Finuge",
                    "Firies",
                    "Fossa",
                    "An Gaeltacht",
                    "Gale Rangers",
                    "Glenbeigh-Glencar",
                    "Glenflesk", 
                    "Gneeveguilla",
                    "John Mitchels",
                    "Keel",
                    "Kenmare",
                    "Kerins O'Rahilly\'s",
                    "Kilcummin",
                    "Kilgarvan",
                    "Killarney Legion",
                    "Kilmoyley",
                    "Knockanure",
                    "Knocknagoshel",
                    "Ladys Walk",
                    "Laune Rangers",
                    "Lispole",
                    "Listowel Emmets",
                    "Listry",
                    "Lixnaw",
                    "Mid Kerry",
                    "Milltown/Castlemaine",
                    "Moyvane",
                    "Na Gaeil",
                    "Rathmore",
                    "Renard",
                    "Scartaglin", 
                    "Skellig Rangers", 
                    "Sneem", 
                    "South Kerry", 
                    "Spa",
                    "St Brendan's",
                    "St. Michael\'s/Foilmore",
                    "St Patrick's, Blennerville",
                    "St Patrick's (East Kerry)",
                    "St Senan's",
                    "Tarbert",
                    "Templenoe",
                    "Tralee Mitchels",
                    "Tuosist",
                    "Valentia",
                    "Waterville",
                    "West Kerry"]

    config.kildare = ["Allenwood",
                      "Ardclough",
                      "Athgarvan",
                      "Athy",
                      "Ballykelly",
                      "Ballymore Eustace",
                      "Ballyteague",
                      "Broadford",
                      "Capagh", 
                      "Caragh",
                      "Carbury",
                      "Castledermot",
                      "Castlemitchell",
                      "Celbridge",
                      "Cill Daingin",
                      "Clane",
                      "Clogherinkoe",
                      "Coill Dubh",
                      "Confey",
                      "Curragh Camp",
                      "Eadestown",
                      "Ellistown",
                      "Grangeolvin",
                      "Johnstownbridge",
                      "Kilcock",
                      "Kilcullen",
                      "Kill",
                      "Leixlip", 
                      "Maynooth",
                      "Military College",
                      "Milltown",
                      "Monasterevin",
                      "Moorefield",
                      "Naas",
                      "Nurney",
                      "Raheens",
                      "Rathangan",
                      "Rathcoffey",
                      "Raheen",
                      "Robertstown",
                      "Roseberry",
                      "Round Towers",
                      "Sallins",
                      "Sarsfields",
                      "St Edward\'s",
                      "St Kevin\'s",
                      "St Laurence\'s",
                      "Staffan",
                      "Suncroft",
                      "Twomilehouse"]

    config.kilkenny = ["Ballyhale Shamrocks",
                       "Bennettsbridge",
                       "Blacks & Whites",
                       "Carrickshock",
                       "Carrigeen",
                       "Clara",
                       "Cloneen",
                       "Conahy Shamrocks",
                       "Danesfort",
                       "Dicksboro", 
                       "Dunnamaggin",
                       "Emeralds",
                       "Erin\'s Own",
                       "Galmoy",
                       "Glenmore",
                       "Graiguenamanagh",
                       "Graigue-Ballycallen",
                       "James Stephens",
                       "John Lockes",
                       "Kilmacow",
                       "Lisdowney",
                       "Mooncoin",
                       "Muckalee",
                       "Mullinavat",
                       "O'Loughlin Gaels",
                       "Piltown",
                       "Railyard",
                       "Rower-Inistiogue",
                       "Slieverue",
                       "St Lachtain\'s",
                       "St Martin\'s",
                       "St Patrick\'s, Ballyraggett",
                       "Thomastown",
                       "Threecastles",
                       "Tullaroan",
                       "Tullogher-Rosbercon",
                       "Young Irelands",
                       "Windgap"]

    config.laois = ["Abbeyleix",
                    "Annanough", 
                    "Arles/Kilcruise", 
                    "Arles/Killeen", 
                    "Ballinakill", 
                    "Ballyfin", 
                    "Ballylinan", 
                    "Ballypickas", 
                    "Ballyroan Abbey",
                    "Ballyroan",
                    "Barrowhouse",
                    "Borris-in-Ossory",
                    "Camross",
                    "Castletown",
                    "Clonad",
                    "Clonaslee-St.Manmans",
                    "Clough/Ballacolla",
                    "Courtwood",
                    "Crettyard",
                    "Emo",
                    "Errill",
                    "Graiguecullen",
                    "Harps",
                    "The Heath",
                    "Kilcavan",
                    "Kilcotton",
                    "Killeshin",
                    "Kyle",
                    "Mountmellick",
                    "O\'Dempseys",
                    "Park/Ratheniska",
                    "Portlarington",
                    "Portlaoise",
                    "Rathdowney",
                    "Rathdowney-Errill",
                    "The Rock",
                    "Rosenallis",
                    "Shanahoe",
                    "Slieve Bloom",
                    "Spink",
                    "St. Fintans, Colt",
                    "St Fintans, Mountrath",
                    "St Joseph\'s",
                    "Stradbally",
                    "Timahoe",
                    "Tinnahinch",
                    "Trumera"]

    config.leitrim = ["Allen Gaels",
                      "Annaduff",
                      "Aughavas", 
                      "Aughawillan",
                      "Aughnasheelin",
                      "Balinaglera",
                      "Bornacoola",
                      "Carrigallen",
                      "Cloone",
                      "Drumkeerin",
                      "Drumreilly",
                      "Eslin",
                      "Glencar-Manorhamilton",
                      "Glenfarne/Kiltyclogher",
                      "Gortletteragh",
                      "Kiltubrid",
                      "Leitrim Gaels",
                      "Melvin Gaels",
                      "Mohill",
                      "Sean O'Heslins",
                      "St Caillin\'s",
                      "St Mary's Kiltoghert",
                      "St Osnett\'s",
                      "St Patrick\'s"]

    config.limerick = ["Abbey Sarsfields",
                       "Adare",
                       "Ahane",
                       "Askeaton",
                       "Athea",
                       "Ballinacurra Gaels",
                       "Ballybricken",
                       "Ballybrown",
                       "Ballylanders", 
                       "Ballysteen", 
                       "Banogue", 
                       "Blackrock", 
                       "Bruff", 
                       "Bruree", 
                       "Caherconlish", 
                       "Caherline", 
                       "Camogue Rovers",
                       "Cappagh",
                       "Cappamore",
                       "Castletown/Ballyagran",
                       "Claughaun",
                       "Crecora",
                       "Croagh/Kilfinny",
                       "Croom",
                       "Doon",
                       "Dromcollogher/Broadford",
                       "Dromin/Athllaca",
                       "Effin",
                       "Fedamore",
                       "Feenagh/Kilmeedy",
                       "Feoghanagh/Castlemahon",
                       "Fr Casey\'s, Abbeyfeale",
                       "Galbally",
                       "Galtee Gaels",
                       "Garryspillane",
                       "Gerald Griffiths",
                       "Glenroe",
                       "Glin",
                       "Granagh/Ballingarry",
                       "Hospital/Herbertstown",
                       "Kilcornan",
                       "Kildimo",
                       "Kileedy",
                       "Kilmallock",
                       "Kilteely-Dromkeen",
                       "Knockaderry", 
                       "Knockainey", 
                       "Knockane", 
                       "Milford", 
                       "Monagea", 
                       "Monaleen", 
                       "Mountcollins",
                       "Mungret St Paul\'s",
                       "Murroe/Boher",
                       "Na Piarsaigh",
                       "Newcastle West",
                       "Old Christians",
                       "Oola",
                       "Pallasgreen",
                       "Pallaskenry",
                       "Patrickswell",
                       "Saint Kieran's",
                       "Saint Mary\'s/Sean Finn\'s",
                       "South Liberties",
                       "St Patrick\'s",
                       "St. Senan\'s",
                       "Staker Wallace",
                       "Templeglantine",
                       "Tournafulla",
                       "Treaty Gaels Camogie Club"]

      config.longford = ["Abbeylara",
                         "Ballymore",
                         "Ballymahon",
                         "Carrickedmond",
                         "Cashel",
                         "Clonguish",
                         "Colmcille",
                         "Dromard",
                         "Killoe Young Emmets",
                         "Fr Manning Gaels",
                         "Grattan Óg",
                         "Kenagh",
                         "Legan Sarsfields",
                         "Longford Slashers",
                         "Mostrim",
                         "Moydow Harpers",
                         "Rathcline",
                         "Seán Connollys",
                         "Shroid Slashers",
                         "St Brigid\'s, Killashee",
                         "St Columba\'s, Mullinalaghta",
                         "St Mary\'s, Granard",
                         "St Munis\', Forgney",
                         "St Patrick\'s, Ardagh",
                         "Western Gaels",
                         "Wolfe Tones (Mostrim)"]

      config.louth = ["Annaghminnion Rovers",
                      "Na Piarsaigh",
                      "Clan na Gael",
                      "Cooley Kickhams",
                      "Cuchulainn Gaels",
                      "Dreadnots",
                      "Dowdallshill",
                      "Dundalk Gaels",
                      "Dundalk Young Irelands",
                      "Geraldines",
                      "Glen Emmets",
                      "Glyde Rangers",
                      "Hunterstown Rovers",
                      "John Mitchells",
                      "Kilkerley Emmets",
                      "Knockbridge",
                      "Lannleire",
                      "Mattock Rangers",
                      "Naomh Fhionnbarra",
                      "Naomh Máirtín",
                      "Naomh Malachi",
                      "Naomh Moninne",
                      "Newtown Blues",
                      "O'Connells",
                      "Oliver Plunketts",
                      "O'Raghallaighs",
                      "Pearse Óg",
                      "Roche Emmets",
                      "Sean MacDermott's",
                      "Seán O'Mahony\'s",
                      "Stabannon Parnells",
                      "St Bride\'s",
                      "St Fechin\'s",
                      "St Joseph\'s",
                      "St Kevin\'s",
                      "St. Mary\'s, Ardee",
                      "St Mochta\'s",
                      "St Nicholas\'",
                      "St Patrick\'s",
                      "Westerns",
                      "Wolfe Tones"]

      config.mayo = ["Achill",
                     "Ardagh",
                     "Ardnaree Sarsfields",
                     "Aghamore",
                     "Balla",
                     "Ballaghadereen",
                     "Ballina Stephenites GFC",
                     "Ballina James Stephens HC",
                     "Ballinrobe",
                     "Ballintubber",
                     "Ballycastle",
                     "Ballycroy",
                     "Ballyhaunis",
                     "Ballyvary",
                     "Belmullet",
                     "Bohola Moy Davitts",
                     "Bonniconlon",
                     "Breaffy",
                     "Burrishoole",
                     "Caiseal Gaels HC",
                     "Castlebar Mitchels",
                     "Castlebar HC",
                     "Charlestown Sarsfields",
                     "Cill Chomáin",
                     "Claremorris",
                     "Crossmolina Deel Rovers",
                     "Davitts",
                     "Eastern Gaels",
                     "Garrymore",
                     "Islandeady",
                     "Hollymount/Carramore",
                     "Kilfian",
                     "Killala",
                     "Kilmeena",
                     "Kilmovee Shamrocks",
                     "Kiltane",
                     "Kiltimagh",
                     "Knockmore",
                     "Lacken",
                     "Lahardane McHales",
                     "Louisburgh",
                     "Mayo Gaels",
                     "Moygownagh",
                     "Moytura HC",
                     "Parke-Keelogues-Crimlin",
                     "Shrule-Glencorrib",
                     "Swinford",
                     "The Neale",
                     "Tooreen HC",
                     "Tuar Mhic Éadaigh",
                     "Westport"]

      config.meath = ["Ballinabrackey",
                      "Ballinlough",
                      "Ballivor",
                      "Bective",
                      "Blackhall Gaels",
                      "Boardsmill",
                      "Carnaross",
                      "Castletown",
                      "Clann na nGael",
                      "Clonard",
                      "Cortown",
                      "Curraha",
                      "Donaghmore/Ashbourne",
                      "Drumbaragh",
                      "Drumconrath",
                      "Drumree",
                      "Dunderry",
                      "Dunsany",
                      "Duleek/Bellewstown",
                      "Dunshaughlin",
                      "Gaeil Colmcille",
                      "Kilbride",
                      "Kildalkey",
                      "Killyon",
                      "Kilmainham",
                      "Kilmainhamwood",
                      "Kilmessan",
                      "Kilskyre",
                      "Kiltale",
                      "Longwood",
                      "Meath Hill",
                      "Moynalty",
                      "Moynalvey",
                      "Moylagh",
                      "Na Fianna",
                      "Navan O'Mahony's",
                      "Nobber",
                      "Oldcastle",
                      "Rathkenny",
                      "Rathmolyon",
                      "Ratoath",
                      "Seneschalstown",
                      "Simonstown Gaels",
                      "Skryne",
                      "Slane",
                      "St Brigid's",
                      "St Colmcille's",
                      "St Mary's",
                      "St Michael's",
                      "St Patrick's",
                      "St Paul's",
                      "St Peter's, Dunboyne",
                      "St Ultan's",
                      "St Vincent's",
                      "Summerhill",
                      "Syddan",
                      "Trim",
                      "Walterstown",
                      "Wolfe Tones"]

      config.monaghan = ["Aghabog",
                         "Aughnamullen",
                         "Ballybay Brothers Pearses",
                         "Blackhill",
                         "Carrickmacross Emmets",
                         "Castleblayney Faughs",
                         "Clontibret O'Neills",
                         "Clones",
                         "Corduff Gales",
                         "Cremartin Shamrocks",
                         "Currin",
                         "Donaghmoyne",
                         "Doohamlet O'Neills",
                         "Drumhowan Geraldines",
                         "Éire Óg",
                         "Emyvale",
                         "Fergal O'Hanlon's",
                         "Gaeil Truicha",
                         "Inniskeen",
                         "Killanny Geraldines",
                         "Killeevan",
                         "Latton O'Rahilly's",
                         "Magheracloone Mitchells",
                         "Monaghan Harps",
                         "Oram",
                         "Rockcorry",
                         "Scotstown",
                         "Seán McDermott's",
                         "Toome",
                         "Tyholland"]

      config.offaly = ["Ballinamere",
                       "Ballycommon",
                       "Ballycumber",
                       "Ballyfore",
                       "Ballyskenagh",
                       "Ballinagar",
                       "Belmont",
                       "Birr",
                       "Bracknagh",
                       "Brosna Gaels",
                       "Cappincur",
                       "Clara",
                       "Clareen",
                       "Clonbullogue",
                       "Coolderry",
                       "Daingean",
                       "Doon",
                       "Drumcullen",
                       "Edenderry",
                       "Erin Rovers",
                       "Ferbane",
                       "Gracefield",
                       "Kilcormac/Killoughey", 
                       "Killeigh", 
                       "Kilurin", 
                       "Kinnitty", 
                       "Lusmagh", 
                       "Raheen", 
                       "Rhode", 
                       "Shamrocks", 
                       "Shannonbridge",
                       "Shinrone",
                       "St Carthage",
                       "St Rynagh's",
                       "Tubber",
                       "Tullamore",
                       "Walsh Island"]

      config.roscommon = ["Athleague",
                          "Boyle",
                          "Clann na nGael",
                          "Ballinameen",
                          "Castlerea/St Kevin\'s",
                          "Creggs",
                          "Éire Óg",
                          "Elphin",
                          "Four Roads",
                          "Fuerty",
                          "Kilbride",
                          "Kilglass Gaels",
                          "Kilmore",
                          "Michael Glaveys",
                          "Oran Hurling",
                          "Oran Football",
                          "Padraig Pearses",
                          "Roscommon Gaels",
                          "Shannon Gaels",
                          "St Aidan\'s",
                          "St Barry\'s",
                          "St Brigid\'s",
                          "St Ciaran\'s",
                          "St Croan\'s",
                          "St Dominic\'s",
                          "St Faithleach\'s",
                          "St Joseph\'s",
                          "St Michael\'s",
                          "St Ronan\'s",
                          "Shannon Gaels",
                          "Strokestown",
                          "Tremane",
                          "Tulsk Lord Edwards",
                          "Western Gaels"]

      config.sligo = ["Ballisodare",
                      "Ballymote",
                      "Bunninadden",
                      "Calry/St Joseph\'s",
                      "Castleconnor",
                      "Cloonacool",
                      "Coolaney/Mullinabreena",
                      "Coolera/Strandhill",
                      "Curry",
                      "Drumcliffe/Rosses Point",
                      "Easkey",
                      "Eastern Harps",
                      "Enniscrone/Kilglass",
                      "Geevagh",
                      "Naomh Eoin",
                      "Owenmore Gaels",
                      "Shamrock Gaels",
                      "St Farnan's",
                      "St John\'s",
                      "St Mary\'s",
                      "St Michael\'s",
                      "St Molaise Gaels",
                      "St Patrick\'s",
                      "Tourlestrane",
                      "Tubbercurry",
                      "Western Gaels"]

      config.tipperary = ["Aherlow",
                          "Ardfinnan",
                          "Arravale Rovers",
                          "Ballina",
                          "Ballinahinch",
                          "Ballingarry",
                          "Ballybacon-Grange",
                          "Ballylooby-Castlegrace",
                          "Ballyneale",
                          "Ballyporeen",
                          "Boherlahan-Dualla",
                          "Borrisokane",
                          "Borris-Ileigh",
                          "Burgess",
                          "Cahir",
                          "Cappawhite",
                          "Carrick Davins",
                          "Carrick Swans",
                          "Cashel King Cormacs",
                          "Clerihan",
                          "Clonakenny",
                          "Clonmel Commercials",
                          "Clonmel Óg",
                          "Clonoulty-Rossmore",
                          "Drom/Inch",
                          "Dúrlas Óg",
                          "Éire Óg/Annacarty",
                          "Emly",
                          "Fethard",
                          "Fr Sheehy's",
                          "Galtee Rovers",
                          "Glengar",
                          "Golden/Kilfeakle",
                          "Gortnahoe-Glengoole",
                          "Grangemockler",
                          "Holycross/Ballycahill",
                          "Inane Rovers",
                          "JK Bracken's",
                          "Kildangan",
                          "Killea",
                          "Killenaule",
                          "Kilruane MacDonagh's",
                          "Kilsheelan-Kilcash",
                          "Knockavilla-Donaskeigh Kickhams",
                          "Knock",
                          "Knockshegowna",
                          "Lattin-Cullen",
                          "Lorrha-Dorrha",
                          "Loughmore/Castleiney",
                          "Marlfield",
                          "Moneygall",
                          "Moycarkey-Borris",
                          "Moyle Rovers",
                          "Moyne-Templetuohy",
                          "Mullinahone",
                          "Nenagh Éire Og",
                          "Newcastle",
                          "Newport",
                          "Portroe",
                          "Rockwell Rovers",
                          "Roscrea",
                          "Rosegreen",
                          "Sean Treacy's",
                          "Shannon Rovers",
                          "Silvermines",
                          "Skeheenarinky",
                          "Solohead",
                          "St Mary's Clonmel",
                          "St Patrick\'s",
                          "Templederry",
                          "Thomas MacDonagh\'s",
                          "Thurles Gaels",
                          "Thurles Sarsfields",
                          "Toomevara",
                          "Upperchurch"]

      config.tyrone = ["Aghaloo O'Neills",
                       "Aghyaran St. Davog's",
                       "Ardboe O'Donovan Rossa",
                       "Augher St. Macartan's",
                       "Badoney Ladies GFC",
                       "Beragh Red Knights",
                       "Brackaville Owen Roes",
                       "Brocagh Emmetts",
                       "Camowen Gaels HC",
                       "Carrickmore St. Colmcille's",
                       "Castlederg St. Eugene's",
                       "Clann na nGael",
                       "Clogher Éire Óg",
                       "Clonoe O'Rahilly's",
                       "Coalisland Na Fianna",
                       "Cookstown Fr. Rock's",
                       "Derrylaughan Kevin Barrys",
                       "Derrytresk Fir An Chnoic",
                       "Donaghmore St. Patrick's",
                       "Dregish Pearse Og",
                       "Dromore Naomh Eoin HC",
                       "Dromore St. Dympna's",
                       "Drumquin Wolfe Tones",
                       "Drumragh Sarsfields",
                       "Dungannon Thomas Clarkes",
                       "Dungannon Eoghan Ruadh HC", 
                       "Edendork St. Malachy's", 
                       "Eglish St. Patrick's", 
                       "Eire Óg Carrickmore HC", 
                       "Errigal Ciarán", 
                       "Eskra Emmetts", 
                       "Fintona Pearses", 
                       "Fintona Setanta HC", 
                       "Galbally Pearses", 
                       "Glenelly St. Joseph's",
                       "Gortin St. Patrick's",
                       "Kildress Wolfe Tones",
                       "Killeeshil St. Mary's",
                       "Killyclogher St. Mary's",
                       "Killyman St. Mary's",
                       "Loughmacrory St. Teresa's",
                       "Moortown St. Malachy's",
                       "Moy Tir na nOg",
                       "Naomh Colmcille HC",
                       "Newtownstewart St. Eugene's",
                       "Omagh St. Enda's",
                       "Owen Roe O'Neill's, Leckpatrick",
                       "Pomeroy Plunketts",
                       "Rock St. Patrick's",
                       "St Patricks, Greencastle",
                       "Sperrin Óg",
                       "Stewartstown Harps",
                       "Strabane Shamrocks HC",
                       "Strabane Sigersons",
                       "Tattyreagh St. Patrick's",
                       "Trillick St. Macartan's",
                       "Urney St. Columba's"]

    config.waterford = ["Abbeyside-Ballinacourty",
                       "Afane/Cappoquin",
                       "Ardmore",
                       "Ballinameela",
                       "Ballyduff Lower",
                       "Ballyduff Upper",
                       "Ballygunner",
                       "Ballysaggart",
                       "Brickey Rangers",
                       "Butlerstown",
                       "Colligan Emmets",
                       "Clashmore-Kinsalebeg",
                       "Clonea-Rathgormack",
                       "De La Salle",
                       "Dungarvan",
                       "Dunhill",
                       "Erins Hope Dungarvan",
                       "Erin's Own",
                       "Fenor",
                       "Ferrybank",
                       "Gaultier",
                       "Geraldines",
                       "John Mitchel's",
                       "Kilgobinet",
                       "Kill",
                       "Kilmacthomas",
                       "Kilrossanty",
                       "Lismore",
                       "Modeligo",
                       "Mount Melleray",
                       "Mount Sion",
                       "The Nire-Fourmilewater",
                       "Passage",
                       "Portlaw",
                       "Rinn Ó gCuanach",
                       "Roanmore",
                       "Shandon Rovers",
                       "Sliabh gCua-Saint Mary's",
                       "Stradbally",
                       "St Molleran's",
                       "St Paul's",
                       "St Saviour's",
                       "Shamrocks",
                       "Tallow",
                       "Tourin/Ballinwillan",
                       "Tramore"]

      config.westmeath = ["Athlone",
                          "Ballinagore",
                          "Ballymore",
                          "Ballycomoyle",
                          "Ballynacargy",
                          "Brownstown",
                          "Bunbrosna",
                          "Castledaly",
                          "Castlepollard",
                          "Castletown/Finea/Coole/Whitehall",
                          "Castletown-Geoghegan",
                          "Caulry",
                          "Clonkill",
                          "Coralstown-Kinnegad",
                          "Crookedwood",
                          "Cullion",
                          "Delvin",
                          "The Downs",
                          "Garrycastle", 
                          "Kilbeggan Shamrocks", 
                          "Killucan", 
                          "Lough Lene Gaels", 
                          "Loughnavalley", 
                          "Maryland", 
                          "Milltown",
                          "Milltownpass",
                          "Moate All Whites",
                          "Mullingar Shamrocks",
                          "Raharney",
                          "Ringtown",
                          "Rosemount",
                          "St Brigids\'s",
                          "St. Fintan\'s, Multyfarnham",
                          "St Joseph\'s",
                          "St Loman\'s, Mullingar",
                          "St Malachy\'s",
                          "St. Mary\'s, Rochfortbridge",
                          "St Oliver Plunkett\'s",
                          "St Paul\'s",
                          "Shandonagh",
                          "Southern Gaels",
                          "Tang",
                          "Tubberclair",
                          "Turin",
                          "Tyrrellspass"]

      config.wexford = ["Adamstown",
                       "Ballyfad", 
                       "Ballyhogue", 
                       "Bannow-Ballymitty", 
                       "Blackwater St Brigids", 
                       "Buffer's Alley", 
                       "Castletown/Liam Mellows", 
                       "Clonard", 
                       "Clonee", 
                       "Clongeen", 
                       "Cloughbawn",
                       "Craanford",
                       "Crossabeg-Ballymurn",
                       "Davidstown-Courtnacuddy",
                       "Duffry Rovers",
                       "Faythe Harriers",
                       "Ferns St Aidan\'s",
                       "Fethard St Mogue\'s",
                       "Geraldine O'Hanrahans",
                       "Glynn-Barntown",
                       "Gusserane O'Rahilly\'s",
                       "Horeswood",
                       "HWH Bunclody",
                       "Kilanerin–Ballyfad",
                       "Kilmore",
                       "Marshalstown-Castledockrell",
                       "Naomh Éanna, Gorey",
                       "Our Lady\'s Island",
                       "Oulart the Ballagh",
                       "Oylegate-Glenbrien",
                       "Rapparees-Starlights",
                       "Ratharogue-Cushinstown",
                       "Rathnure St Anne\'s",
                       "Réalt Na Mara-Ballygarrett",
                       "Sarsfields",
                       "Shamrocks",
                       "Shelmaliers",
                       "St Anne\'s Rathangan",
                       "St Fintan\'s",
                       "St Joseph\'s",
                       "St James\'",
                       "St Martin\'s",
                       "St Mary\'s Maudlintown",
                       "St Mary\'s Rosslare",
                       "Taghmon-Camross",
                       "Tara Rocks",
                       "Volunteers St Johns"]

      config.wicklow = ["Annacurra",
                        "Arklow Rock Parnells",
                        "Arklow Geraldines, Ballmoney",
                        "Avondale",
                        "Ballinacor",
                        "Baltinglass",
                        "Blessington",
                        "Bray Emmets",
                        "Carnew Emmets",
                        "Enniskerry",
                        "Éire Óg Greystones",
                        "Fergal Óg\'s",
                        "Glenealy",
                        "Hollywood",
                        "Kiltegan",
                        "Lacken",
                        "Newtownmountkennedy",
                        "Rathnew",
                        "Tinahely",
                        "An Tóchar",
                        "Shillelagh",
                        "St Patrick\'s, Wicklow",
                        "Valleymount",
                        "Kilcoole"]

  end
end
