require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Gatabase
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Do not swallow errors in after_commit/after_rollback callbacks.
    config.active_record.raise_in_transactional_callbacks = true

    config.counties = ["Antrim",
                       "Armagh",
                       "Carlow",
                       "Cavan",
                       "Clare",
                       "Cork",
                       "Derry",
                       "Donegal",
                       "Down",
                       "Dublin",
                       "Fermanagh",
                       "Galway",
                       "Kerry",
                       "Kildare",
                       "Kilkenny",
                       "Laois",
                       "Leitrim",
                       "Limerick",
                       "Longford",
                       "Louth",
                       "Mayo",
                       "Meath",
                       "Monaghan",
                       "Offaly",
                       "Roscommon",
                       "Sligo",
                       "Tipperary",
                       "Tyrone",
                       "Waterford",
                       "Westmeath",
                       "Wexford",
                       "Wicklow"]

    config.antrim = ["All Saints",
                     "Ardoyne Kickhams",
                     "Cardinal O'Donnells",
                     "Ballymoney",
                     "Carey Faughs",
                     "Clooney Gaels HC",
                     "Con Magees",
                     "Cushendun Emmets",
                     "Creggan Kickhams",
                     "Dunloy Cuchullains",
                     "Erin\'s Own",
                     "Éire Óg",
                     "Gort na Móna",
                     "Glen Rovers",
                     "Glenshesk",
                     "Henry Joy McCracken\'s",
                     "John Mitchel\'s",
                     "Lagmore Gaels",
                     "Lámh Dhearg",
                     "Laochra Loch Lao",
                     "Latharna Óg",
                     "Loch Mór Dál gCais",
                     "McQuillan\'s",
                     "Michael Davitt\'s",
                     "Michael Dwyer\'s",
                     "Na Fuiseoige",
                     "Naomh Eoin",
                     "Naomh Mhuire",
                     "O\'Donovan Rossa",
                     "Oisín Glenariff",
                     "Patrick Pearse\'s",
                     "Patrick Sarsfields",
                     "Roger Casement\'s",
                     "Ruairí Óg",
                     "Sean Martin\'s",
                     "Sean McDermott\'s",
                     "Sean Stinson\'s",
                     "Loughgiel Shamrocks",
                     "Shane O'Neill\'s",
                     "St Agnes'",
                     "St Brigid\'s",
                     "St Comgall\'s",
                     "St Enda\'s",
                     "St Ergnat\'s",
                     "St Gall\'s",
                     "St James\'",
                     "St John\'s",
                     "St Joseph\'s",
                     "St Malachy\'s",
                     "St Mary\'s",
                     "St Mary's GFC",
                     "St Mary\'s",
                     "St Paul\'s",
                     "St Patrick\'s",
                     "St Teresa\'s",
                     "Tir-na-nÓg"]

    config.armagh = ["O'Neill\'s GAC, An Port Mór",
                     "Annaghmore Pearses Gaelic Football Club (GFC)",
                     "Cúchulainn\'s Hurling Club (HC)",
                     "Armagh Harps",
                     "Pearse Óg Gaelic Athletic Club (GAC)",
                     "Ballyhegan Davitts",
                     "Ballymacnab Round Towers",
                     "St Brenda\'s Camogie Club",
                     "Ballymacnab",
                     "Belleeks Laurence O'Toole\'s",
                     "St. Patrick\'s, Carrickcruppen",
                     "Clady Sean South\'s",
                     "Shane O'Neill\'s, Camloch",
                     "Craobh Rua Camloch HC",
                     "Clann Éireann Lurgan",
                     "Clonmore Robert Emmet\'s",
                     "Collegeland O'Rahilly\'s",
                     "Thomas Davis Corrinshego",
                     "Éire Óg Craigavon",
                     "Crosmaglen Rangers",
                     "Cullaville Blues",
                     "Phelim Brady\'s Darkley",
                     "Derrymacash St Enda\'s Camogie Club",
                     "Derrynoose St Mochua\'s",
                     "Dorsey Emmet\'s",
                     "Dromintee St. Patrick\'s",
                     "Forkhill Peadar Ó Doirnín",
                     "Granemore St Mary\'s",
                     "Grange St. Colmcille\'s",
                     "High Moss Sarsfields",
                     "Keady Michael Dwyer\'s",
                     "Keady Lámh Dhearg HC",
                     "Killeavy St. Monina\'s",
                     "Lissummon",
                     "Lurgan Clan na Gael",
                     "Lurgan Sean Treacy\'s HC",
                     "Madden Raparees",
                     "St Joseph\'s Camogie Club, Madden",
                     "Maghery Sean MacDermott\'s GAC",
                     "Middletown Eoghan Ruadh (football)",
                     "Na Fianna (hurling)",
                     "St John\'s (camogie)",
                     "Mullaghbawn Cuchullian\'s",
                     "Mullabrack O'Donovan Rossa",
                     "St Michael\'s, Newtownhamilton",
                     "St Michael\'s GFC, Killean",
                     "St. Patrick\'s Cullyhanna",
                     "St. Paul\'s Lurgan",
                     "St Peter\'s GAC Lurgan",
                     "Portadown St Malachy\'s HC",
                     "Portadown Tír na nÓg",
                     "Poyntzpass Redmond O'Hanlon\'s",
                     "Silverbridge Harps",
                     "Tullysaran O\'Connell\'s",
                     "Whitecross St. Killian\'s",
                     "Wolfe Tones, Derrymacash"]

    config.carlow = ["Asca",
                     "Ballinabranna",
                     "Ballon",
                     "Ballinkillen",
                     "Carlow Town HC",
                     "Clonmore",
                     "Éire Óg",
                     "Erin\'s Own",
                     "Fenagh",
                     "Fighting Cocks",
                     "Grange",
                     "Kildavin/Clonegal",
                     "Kilbride",
                     "Leighlinbridge",
                     "Milford",
                     "Mount Leinster Rangers",
                     "Michael Davitts",
                     "Naomh Bríd",
                     "Naomh Eoin",
                     "O'Hanrahan\'s",
                     "Old Leighlin",
                     "Palatine",
                     "Rathvilly",
                     "St Andrew\'s",
                     "St Mullin\'s",
                     "St Patrick\'s",
                     "Tinryland"]

    config.cavan = ["Arvagh",
                    "Bailieboro Shamrocks",
                    "Ballinagh",
                    "Ballyhaise",
                    "Belturbet Rory O\'Moore\'s",
                    "Butlersbridge",
                    "Castlerahan",
                    "Cavan Gaels",
                    "Cootehill Celtic",
                    "Corlough",
                    "Cornafean",
                    "Crosserlough",
                    "Mullagh Cúchullains",
                    "Denn",
                    "Drumalee",
                    "Drumgoon",
                    "Drumlane",
                    "Drung",
                    "East Cavan Gaels GAA Hurling Club", 
                    "Gowna", 
                    "Kildallon", 
                    "Kill Shamrocks", 
                    "Killeshandra", 
                    "Killinkere", 
                    "Killygarry",
                    "Kingscourt Stars",
                    "Knockbride",
                    "Lacken Celtic",
                    "Laragh United",
                    "Lavey",
                    "Macauley Geals, Mullahorn",
                    "Maghera MacFinns",
                    "Mountnugent",
                    "Mullahoran",
                    "Munterconnaught",
                    "Ramor United",
                    "Redhills",
                    "Shannon Gaels",
                    "Shercock",
                    "Swanlinbar St Mary\'s",
                    "Templeport St Aidan\'s"]

    config.clare = ["Ballyea",
                    "Ballyvaughan",
                    "Banner",
                    "Bodyke",
                    "Broadford",
                    "Clarecastle",
                    "Clonboney",
                    "Clondegad",
                    "Clonlara",
                    "Clooneyquin",
                    "Coolmeen",
                    "Cooraclare",
                    "Corofin",
                    "Cratloe",
                    "Crusheen",
                    "Doonbeg",
                    "Éire Óg, Inis",
                    "Ennistymon",
                    "Feakle",
                    "Inagh-Kilnamona",
                    "Kildysart",
                    "Kilfenora",
                    "Kilkee Bealatha",
                    "Killimer",
                    "Killanena",
                    "Kilmaley",
                    "Kilmihil",
                    "Kilmurry Ibrickane",
                    "Kilrush Shamrocks",
                    "Liscannor",
                    "Lissycasey",
                    "Meelick",
                    "Michael Cusack's",
                    "Moy",
                    "Naomh Eoin",
                    "Newmarket-on-Fergus",
                    "O\'Callaghan Mills",
                    "O\'Curry\'s",
                    "Ogonnelloe",
                    "Parteen",
                    "Ruan",
                    "Scariff",
                    "Shannon Gaels",
                    "Sixmilebridge",
                    "Smith O\'Brien\'s",
                    "St Breckan\'s",
                    "St Joseph\'s Doora-Barefield",
                    "St Joseph\'s, Milltown Malbay",
                    "St. Senan\'s, Kilkee",
                    "Tubber",
                    "Tulla",
                    "West Clare Gaels",
                    "Whitegate",
                    "Wolfe Tones na Sionna"]

    config.cork = ["Abbey Rovers",
                   "Adrigole",
                   "Aghabullogue",
                   "Aghada",
                   "Aghinagh",
                   "Araglen",
                   "Argideen Rangers",
                   "Awbeg Rangers",
                   "Ballinacurra",
                   "Ballinascarthy",
                   "Ballincollig",
                   "Ballinhassig",
                   "Ballinora",
                   "Ballinure",
                   "Ballyclough",
                   "Ballydesmond",
                   "Ballygarvan",
                   "Ballygiblin",
                   "Ballyhea",
                   "Ballyhooly",
                   "Ballymartle",
                   "Ballyphehane",
                   "Bandon",
                   "Banteer",
                   "Bantry Blues",
                   "Barryroe",
                   "Belgooly",
                   "Bere Island",
                   "Bishopstown",
                   "Blackrock",
                   "Blarney",
                   "Boherbue",
                   "Brian Dillons",
                   "Bride Rovers",
                   "Buttevant",
                   "Béal Átha\'n Ghaorthaidh",
                   "CIT",
                   "Canovee",
                   "Carbery Rangers",
                   "Carrigaline",
                   "Carrignavar",
                   "Carrigtwohill",
                   "Castlehaven",
                   "Castlelyons",
                   "Castlemagner",
                   "Castlemartyr",
                   "Castletownbere",
                   "Castletownroche",
                   "Charleville",
                   "Churchtown",
                   "Clann na nGael",
                   "Clonakilty",
                   "Clondrohid",
                   "Cloughduv",
                   "Cloyne",
                   "Clyda Rovers",
                   "Cobh",
                   "Courcey Rovers",
                   "Crosshaven",
                   "Cullen",
                   "Deel Rovers",
                   "Delaney Rovers",
                   "Diarmuid Ó Mathúnas",
                   "Dohenys",
                   "Doneraile",
                   "Donoughmore",
                   "Douglas",
                   "Dripsey",
                   "Dromina",
                   "Dromtarriffe",
                   "Dungourney",
                   "Éire Óg",
                   "Erin\'s Own",
                   "Fermoy",
                   "Fr. O\'Callaghan's",
                   "Fr. O\'Neills",
                   "Freemount",
                   "Gabriel Rangers",
                   "Garnish",
                   "Glanmire",
                   "Glanworth",
                   "Gleann na Laoi",
                   "Glen Rovers",
                   "Glenbower Rovers",
                   "Glengarriff",
                   "Glenlara",
                   "Glenville",
                   "Goleen",
                   "Grange",
                   "Grenagh",
                   "Gurranabraher",
                   "Harbour Rovers",
                   "Ilen Rovers", 
                   "Inniscarra",
                   "Iveleary",
                   "Kanturk",
                   "Kilbree",
                   "Kilbrin",
                   "Kilbrittain",
                   "Kildorrery",
                   "Killavullen",
                   "Killeagh",
                   "Kilmacabea",
                   "Kilmeen",
                   "Kilmichael",
                   "Kilmurry",
                   "Kilnamartyra",
                   "Kilshannig",
                   "Kilworth",
                   "Kinsale",
                   "Kiskeam",
                   "Knocknagree",
                   "Laochra Óg",
                   "Liscarroll",
                   "Lisgoold",
                   "Lough Rovers",
                   "Lyre",
                   "Macroom",
                   "Mallow",
                   "Mayfield",
                   "Meelin",
                   "Midleton",
                   "Milford",
                   "Millstreet",
                   "Mitchelstown",
                   "Muintir Bháire",
                   "Na Piarsaigh",
                   "Naomh Abán",
                   "Nemo Rangers",
                   "Newcestown",
                   "Newmarket",
                   "Newtownshandrum",
                   "O\'Donovan Rossa",
                   "Passage West",
                   "Randal Og",
                   "Rathpeacon",
                   "Redmonds",
                   "Rochestown",
                   "Rockchapel",
                   "Russell Rovers",
                   "Sam Maguires",
                   "Sarsfields",
                   "Shamrocks",
                   "Shanballymore",
                   "Shandon Rovers",
                   "Sliabh Rua",
                   "St Catherine\'s",
                   "St Colum\'s",
                   "St Finbarr\'s",
                   "St Ita\'s",
                   "St James\'",
                   "St Marys's",
                   "St Michael's",
                   "St Nicholas'",
                   "St Oliver Plunkett's",
                   "St Vincent's",
                   "Tadhg MacCarthaigh",
                   "Tracton",
                   "Tullylease",
                   "UCC",
                   "Urhan",
                   "Valley Rovers",
                   "Watergrasshill",
                   "White's Cross",
                   "Whitechurch",
                   "Youghal"]

    config.derry = ["Ardmore",
                    "Ballerin",
                    "Ballinascreen",
                    "Ballinderry",
                    "Ballymaguigan",
                    "Banagher",
                    "Bellaghy",
                    "Castledawson",
                    "Claudy",
                    "Craigbane",
                    "Desertmartin",
                    "Doire Colmcille",
                    "Doire Trasna",
                    "Drum",
                    "Drumsurn",
                    "Dungiven",
                    "Eoghan Rua",
                    "Faughanvale",
                    "Foreglen",
                    "Glack",
                    "Glen",
                    "Glenullin",
                    "Greenlough",
                    "Kevin Lynch\'s Hurling Club",
                    "Kilrea",
                    "Lavey",
                    "Limavady",
                    "Lissan",
                    "Loup",
                    "Magherafelt",
                    "Magilligan",
                    "Moneymore",
                    "Na Magha",
                    "Newbridge",
                    "Ógra Colmcille",
                    "Seán Dolans",
                    "Slaughtmanus",
                    "Slaughtneil",
                    "Steelstown",
                    "Swatragh"]

    config.donegal = ["Aodh Ruadh, Ballyshannon",
                      "Ardara",
                      "Buncrana",
                      "Burt",
                      "Carndonagh",
                      "Cloughaneely",
                      "Dungloe",
                      "Fanad Gaels",
                      "Four Masters",
                      "Gaoth Dobhair",
                      "Glenfin",
                      "Glenswilly",
                      "Kilcar",
                      "Killybegs",
                      "Letterkenny Gaels",
                      "Malin",
                      "Milford",
                      "Moville",
                      "Na Dúnaibh (Downings)",
                      "Na Rossa",
                      "Naomh Bríd",
                      "Naomh Colmcille",
                      "Naomh Columba",
                      "Naomh Conaill",
                      "Naomh Muire",
                      "Naomh Pádraig, Lifford",
                      "Naomh Pádraig, Muff",
                      "Naomh Ultan",
                      "Pettigo",
                      "Red Hughs, Killygordon",
                      "Robert Emmet\'s",
                      "Réalt Na Mara, Bundoran",
                      "Setanta",
                      "Seán Mac Cumhaill\'s",
                      "St. Eunan\'s",
                      "St. Mary\'s, Convoy",
                      "St. Michael\'s",
                      "St. Naul\'s",
                      "Termon",
                      "Urris"]

    config.down = ["Aghaderg-Ballyvarley",
                   "An Riocht",
                   "Annaclone",
                   "Annsborough",
                   "Ardglass",
                   "Atticall",
                   "Ballela",
                   "Ballycran",
                   "Ballygalget",
                   "Ballyholland",
                   "Ballykinlar",
                   "Ballymartin",
                   "Bredagh",
                   "Bright",
                   "Bryansford- Website",
                   "Burren",
                   "Carryduff",
                   "Castlewellan",
                   "Clann na Banna",
                   "Clonduff",
                   "Darragh Cross",
                   "Dromara",
                   "Drumaness",
                   "Drumgath",
                   "Dundrum",
                   "Glasdrumman",
                   "Glenn",
                   "Kilclief",
                   "Kilcoo",
                   "Killyleagh",
                   "Liatroim",
                   "Longstone",
                   "Loughinisland",
                   "Mayobridge",
                   "John Mitchel",
                   "Mourne HC",
                   "Newry Bosco",
                   "Newry Shamrocks",
                   "Portaferry",
                   "Rostrevor",
                   "Russell Gaelic Union, Downpatrick",
                   "Saul",
                   "Saval",
                   "St John's",
                   "St Michael's",
                   "St Paul's",
                   "Teconnaught",
                   "Tullylish",
                   "Warrenpoint"]


    config.dublin = ["Adamstown",
                     "Allied Irish Banks",
                     "Ballinteer Saint Johns",
                     "Ballyboden St. Enda's GAA",
                     "Ballyboughal",
                     "Ballyfermot de la Salle", "Ballymun Kickhams",
                     "Bank of Ireland",
                     "Beann Éadair",
                     "Castleknock",
                     "Civil Service GFC",
                     "Civil Service HC",
                     "Clann Mhuire",
                     "Clanna Gael Fontenoy",
                     "Clontarf", 
                     "Commercials Hurling Club",
                     "Craobh Chiaráin",
                     "Croi Ro Naofa",
                     "Crumlin",
                     "Cuala",
                     "Erin go Bragh",
                     "Erin's Hope",
                     "Erin's Isle",
                     "Faughs",
                     "Fingal Ravens, Rolestown",
                     "Fingallians",
                     "Foxrock-Cabinteely",
                     "Garda", "Garristown",
                     "Geraldine Morans",
                     "Good Counsel",
                     "Innisfails",
                     "Kevins",
                     "Kilmacud Crokes",
                     "Liffey Gaels",
                     "Lucan Sarsfields",
                     "Man O'War",
                     "Na Dubh Ghall",
                     "Na Fianna",
                     "Na Gaeil Óga",
                     "Naomh Barróg",
                     "Naomh Caoímhin Cillian",
                     "Naomh Fionnbarra",
                     "St. Maur's",
                     "Naomh Mearnóg",
                     "Naomh Ólaf",
                     "O'Dywer's",
                     "O'Tooles's",
                     "Park Rangers",
                     "Parnells",
                     "St Christophers/Paveh",
                     "Portobello",
                     "Raheny",
                     "Ranelagh Gaels",
                     "Réalt Dearg",
                     "Robert Emmets",
                     "Round Towers Clondalkin",
                     "Round Towers, Lusk",
                     "Rosmini Gaels",
                     "Samildánach CLG Bawnogue",
                     "Scoil Uí Chonaill",
                     "Setanta",
                     "Shankill",
                     "Skerries Harps",
                     "St. Annes",
                     "St Brendan's",
                     "St. Brigids",
                     "St Colmcilles",
                     "St. Finian's",
                     "St. Finnian's",
                     "St Francis Gaels",
                     "St. James Gaels",
                     "St Josephs/OCB",
                     "St Judes",
                     "St. Margarets",
                     "St. Marks Springfield Estate",
                     "St. Marys, Saggart",
                     "St. Monica's",
                     "St Oliver Plunketts/Eoghan Ruadh",
                     "St. Patrick's (D)",
                     "St. Patricks (P)",
                     "St. Peregrines",
                     "St Sylvesters",
                     "St Vincents",
                     "Starlights",
                     "Stars of Erin",
                     "Templeogue Synge Street",
                     "Thomas Davis",
                     "Transport Gaels",
                     "Trinity Gaels",
                     "Tyrrelstown",
                     "UCD",
                     "Wanderers ",
                     "Westmanstown Gaels",
                     "Whitehall Colmcille",
                     "Wild Geese",
                     "Western Gaels"]

    config.fermanagh = ["Teemore Shamrocks",
                        "Irvinestown St Molaise\'s", 
                        "Aughdrumsee St Macartan\'s", 
                        "Derrygonnelly Harps", 
                        "St Patrick\'s Donagh", 
                        "Tempo Maguires",
                        "Enniskillen Gaels",
                        "Roslea Shamrocks",
                        "Erne Gaels",
                        "Derrylin O\'Connell\'s",
                        "Belcoo O\'Rahilly\'s",
                        "Lisbellaw St Patrick\'s",
                        "Belnaleck Art McMurrough\'s",
                        "Maguiresbridge St Mary\'s",
                        "Lisnaskea Emmett\'s Hurling",
                        "Newtownbutler First Fermanagh\'s",
                        "Devenish St Mary\'s",
                        "Kinawley Brian Boru\'s",
                        "St Joseph\'s Ederney",
                        "Lisnaskea Emmett\'s",
                        "Brookeboro Heber Mc Mahons",
                        "Coa O\'Dwyer\'s",
                        "Knocks Grattan\'s"]

    config.galway = ["Abbeyknockmoy",
                     "Ahascragh-Fohenagh",
                     "An Spidéal",
                     "Annaghdown",
                     "Aran Islands",
                     "Ardrahan",
                     "Ballinasloe",
                     "Ballinderreen GAA",
                     "Ballygar",
                     "Barna",
                     "Beagh",
                     "Bearna/Na Forbacha",
                     "Caherlistrane",
                     "Caltra",
                     "Cappataggle",
                     "Carna-Caiseal",
                     "Carnmore",
                     "Carraroe",
                     "Castlegar",
                     "Claregalway",
                     "Clarinbridge",
                     "Clifden",
                     "Clonbur",
                     "Corofin",
                     "Cortoon Shamrocks",
                     "Craughwell",
                     "Dunmore McHales",
                     "Father Griffins-Éire Óg",
                     "Gaeil na Gaillimhe CLG",
                     "Glenamaddy",
                     "Glenysk",
                     "Gort",
                     "Headford",
                     "Kilbeacanty",
                     "Kilconieron",
                     "Kilconly",
                     "Killanin",
                     "Killererin",
                     "Killimor",
                     "Killimordaly",
                     "Kilkerrin-Clonberne",
                     "Kilnadeema-Leitrim",
                     "Kiltormer",
                     "Kinvara",
                     "Liam Mellows",
                     "Loughrea",
                     "Meelick/Eyrecourt",
                     "Menlo Emmet's",
                     "Menlough",
                     "Míchael Breathnach",
                     "Milltown",
                     "Monivea Abbeyknockmoy",
                     "Mountbellew-Moylough",
                     "Moycullen",
                     "Mullagh",
                     "Na Piarsaigh",
                     "Naomh Anna",
                     "Oranmore-Maree",
                     "Oughterard",
                     "Pádraig Pearse's",
                     "Portumna",
                     "Rahoon-Newcastle",
                     "Renvyle",
                     "Salthill-Knocknacarra", 
                     "Sarsfields", 
                     "Skehana", 
                     "Sylane",
                     "St Brendan's",
                     "St Colman's",
                     "St Columba's",
                     "St Gabriel's",
                     "St Grellan's",
                     "St James'",
                     "St Kerill's",
                     "St Mary's, Athenry",
                     "St Michael's", 
                     "St Thomas'", 
                     "Tommy Larkin's", 
                     "Tuam Hurling", 
                     "Tuam Stars",
                     "Turloughmore",
                     "Tynagh-Abbey-Duniry",
                     "Williamstown"]


  end
end
